export const ADD_INGREDIENT="ADD_INGREDIENTS";
export const REMOVE_INGREDIENT="REMOVE_INGREDIENTS";
export const SET_INGEDRIENTS="SET_INGEDRIENTS";
export const ERROR_HANDLER="ERROR_HANDLER";
export const PURCHASE_BURGER_START="PURCHASE_BURGER_START";
export const ORDER_SUCESS="ORDER_SUCESS";
export const ORDER_FAIL="ORDER_FAIL";
export const PURCHASE_NEW="PURCHASE_NEW";